### ISSUE TITLE
Rota que retorne a idade de um usuário

### ISSUE THREAD

**Issue by lucassbeiler** [GustavoConstantini/Noktis#18]
Preciso de uma rota que:
- Receba o token do usuário atual;
- Receba o ID de um outro usuário;
- Calcule a idade através da data de nascimento e retorne a idade desse outro usuário cujo ID foi informado;

NOTA: Issue #6 deve ser concluído antes desse, algumas alterações do issue #18 dependem de alterações do issue #6.

**Comment by lucassbeiler** [comment]
Issue #6 deve ser implementado primeiro.

**Comment by GustavoConstantini** [comment]
done

**Comment by lucassbeiler** [comment]
Reabrindo para verificar a possibilidade de retornar a idade já calculada junto com as demais informações dos usuários.
