### ISSUE TITLE
Filtros no retorno de /users/online

### ISSUE THREAD

**Issue by lucassbeiler** [GustavoConstantini/Noktis#7]
/users/online recebe o token do usuário atual e verifica as preferências de intervalo de idade e distância máxima definidas no banco de dados para aquele usuário e filtra o retorno para mostrar apenas pessoas dentro dos intervalos de idade e distância definidos.

Também seria interessante que /users/online sondasse o perfil do usuário atual e colocasse primeiro no array de retorno as pessoas que apresentam palavras-chave iguais em seus perfis (exemplo de palavras-chave: alguma palavra em comum nas bios, mesma escola/universidade, mesmos hobbies e etc)

**Comment by GustavoConstantini** [comment]
done

**Comment by lucassbeiler** [comment]
UNDONE!
